# Generated by Django 5.0.1 on 2024-01-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_data',
            name='department',
            field=models.CharField(choices=[('Choose department', 'Choose department'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical and Materials Engineering', 'Metallurgical and Materials Engineering'), ('Polymer and Textile Engineering', 'Polymer and Textile Engineering'), ('Architecture', 'Architecture'), ('Building Technology', 'Building Technology'), ('Estate Management', 'Estate Management'), ('Quantity Surveying', 'Quantity Surveying'), ('Surveying and Geoinformatics', 'Surveying and Geoinformatics'), ('Urban and Regional Planning', 'Urban and Regional Planning'), ('Accountancy', 'Accountancy'), ('Banking and Finance', 'Banking and Finance'), ('Business Administration', 'Business Administration'), ('Cooperative Economics and Management', 'Cooperative Economics and Management'), ('Marketing', 'Marketing'), ('Public Administration', 'Public Administration'), ('Pure and Industrial Chemistry', 'Pure and Industrial Chemistry'), ('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Microbiology', 'Microbiology'), ('Physics with Electronics', 'Physics with Electronics'), ('Statistics', 'Statistics'), ('Biological Sciences', 'Biological Sciences'), ('Geology', 'Geology'), ('Science Laboratory Technology', 'Science Laboratory Technology'), ('Food Science and Technology', 'Food Science and Technology'), ('Science Laboratory Technology', 'Science Laboratory Technology')], default='Choose faculty', max_length=100),
        ),
        migrations.AlterField(
            model_name='students_data',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='students_data',
            name='faculty',
            field=models.CharField(choices=[('Choose faculty', 'Choose faculty'), ('Engineering', 'Engineering'), ('Environmental Science', 'Environmental Science'), ('Management Science', 'Management Science'), ('Science and Technology', 'Science and Technology')], default='Choose faculty', max_length=100),
        ),
        migrations.AlterField(
            model_name='students_data',
            name='regNumber',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
