# Generated by Django 5.0.1 on 2024-01-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_students_data_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_data',
            name='otherName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students_data',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='images/student_profile_picture'),
        ),
    ]
