# Generated by Django 5.0.1 on 2024-01-29 17:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_students_data_othername_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_data',
            name='level',
        ),
        migrations.AlterField(
            model_name='students_data',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='images/student_profile_picture', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'PNG', 'jpg', 'jpeg'])]),
        ),
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('courseCode', models.CharField(max_length=20)),
                ('courseTitle', models.CharField(max_length=100)),
                ('scorePerCourse', models.IntegerField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.students_data')),
            ],
        ),
    ]
