# Generated by Django 5.0.1 on 2024-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_students_data_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='scorePerCourse',
            field=models.IntegerField(null=True),
        ),
    ]
