# Generated by Django 5.0.1 on 2024-04-11 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_coursework_scorepercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('level', models.CharField(max_length=100, null=True)),
                ('semester', models.CharField(max_length=100, null=True)),
                ('moduleName', models.CharField(max_length=100)),
                ('urlSubmit', models.URLField(null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.students_data')),
            ],
        ),
    ]
