# Generated by Django 5.0.1 on 2024-04-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='taskStatus',
            field=models.BinaryField(null=True),
        ),
    ]
