# Generated by Django 5.0.1 on 2024-04-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_assessment_taskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='taskStatus',
            field=models.IntegerField(default=0),
        ),
    ]
