# Generated by Django 5.0.1 on 2024-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_assessment_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='taskName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
