# Generated by Django 5.0.1 on 2024-04-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_assessment_taskname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='taskName',
        ),
    ]
