# Generated by Django 5.0.1 on 2024-04-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_assessment_taskname'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_data',
            name='refNumber',
            field=models.IntegerField(null=True),
        ),
    ]
