# Generated by Django 5.0.1 on 2024-04-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_students_data_refnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='regNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
