# Generated by Django 5.0.1 on 2024-04-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_transaction_regnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_data',
            name='refNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
