# Generated by Django 5.0.1 on 2024-04-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_students_data_refnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='remark',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
