# Generated by Django 5.0.1 on 2024-04-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_coursework_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursework',
            name='remark',
        ),
        migrations.AddField(
            model_name='assessment',
            name='remark',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
