# Generated by Django 5.1 on 2024-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_students', models.IntegerField()),
                ('present_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('regNumber', models.IntegerField(unique=True)),
                ('department', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
