# Generated by Django 5.0.7 on 2024-08-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sems_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('privilege_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sems_admin.adminuser'),
        ),
        migrations.DeleteModel(
            name='AdminData',
        ),
    ]
