# Generated by Django 5.0.1 on 2024-01-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
